Make annotation macro derive Canon
dusk-network/kelvin pull request #49
Opened 2020-10-06 23:45 UTC by CPerezz

In order to have Generic and easy-to-implement
`Anotations` which use Canon-derived structures inside, we needed
to have the `Canon` trait implemented for them.

Now the macro derives the Canon trait correctly and it is working
for poseidon252::PoseidonAnnotation which is generated using this
exact macro.

Also the implementation of `Content` has been removed since the
trait has been deprecated.

2020-10-06 23:56 UTC, krl reviewed
LGTM!

2020-10-07 00:13 UTC, krl requested changes
if it just removes the warning without fixing the issue, i'd prefer to keep the warning

2020-10-07 00:39 UTC, CPerezz commented
I can go for it, but depends on how much work you have locally since then we might go in different directions and it might end up in conflicts.

So whatever you prefer.

2020-10-07 00:41 UTC, krl commented
Just keeping it for now is fine, i'm dealing with it in my state of things already.

2020-10-07 11:16 UTC, merged